baseURL = 'https://juanmiguelgarcia.me/'
languageCode = 'en-us'
title = 'Juan M. Garcia'
theme = "freelancer"
[params]
  tagLine = "Software passionate - Entrepreneur - Avocado 🥑"
  homePosts = 3
  homeProjects = 3

  aboutLeft = "Software engineer with more than 11 years experience building web apps. Especialist in JS and all the ecosystem arount it (react, vue, angular, node, nuxt, next...)"
  aboutRight = "Lead experience and specialist in managing teams"

[params.location]
  lineOne = "Christinenstraße 2"
  lineTwo = "Hamburg Germany 21031"

[[params.social]]
  url = ""
  icon_pack = ""
  icon = "github"

[[params.social]]
  url = ""
  icon_pack = ""
  icon = "github"

[params.sbform]
      token = ""

[params.homebutton]
  text = "Download CV"
  link = "void"
  icon = "fa-download"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
